# Generated by Django 3.0 on 2021-03-20 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('udaan_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserQuestionReponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_resp', to='udaan_app.Question')),
                ('quiz_qesponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_resp', to='udaan_app.QuizResponse')),
                ('user_ans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_resp', to='udaan_app.QuestionOptions')),
            ],
        ),
        migrations.AddField(
            model_name='quizresponse',
            name='question_ans',
            field=models.ManyToManyField(related_name='quiz_response', through='udaan_app.UserQuestionReponse', to='udaan_app.Question'),
        ),
        migrations.AddField(
            model_name='quizresponse',
            name='quiz_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_response', to='udaan_app.Quiz'),
        ),
    ]
