# Generated by Django 3.0 on 2021-03-20 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('udaan_app', '0002_auto_20210320_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresponse',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_response', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
