# Generated by Django 3.0 on 2021-03-07 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210307_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_temp_id',
        ),
    ]
